import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/navbar'
import { useEffect, useState } from 'react'
import { useAccount } from "wagmi";
import axios from 'axios';
import { User, HousesProps, MyHouse } from "../types/index";
import Loading from '@/components/loading'
import HomeBody from '@/components/home'
import Popup from '@/components/modal'
import { readContract, writeContract } from '@wagmi/core'
import contractInfo from "../../contractInfo/contract.json";
import { toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { isConnected, address } = useAccount();
  const [user, setUser] = useState<User | undefined>(undefined);
  const [userExist, setUserExist] = useState(false);
  const [houses, setHouses] = useState<Array<HousesProps> | undefined>(undefined);
  const [isLoading, setIsLoading] = useState(true);
  const [showPopUp, setShowPopUp] = useState(false);
  const [myHouse, setMyHouse] = useState<MyHouse>({ tokenUri: "", description: "", buttonOk: "", buttonCancel: "", onCancel: () => { }, onAccept: () => { } });

  const tryToBuy = (house: HousesProps, user: User) => {
    setShowPopUp(true)
    setMyHouse({
      tokenUri: house.tokenUri,
      description: `${house.name}: ${house.description}.\n¿Te gusta este inmueble?`,
      buttonOk: "Solicitar",
      buttonCancel: "Cancelar",
      onCancel: () => {
        console.log("canceled")
        setShowPopUp(false);
      },
      onAccept: async () => {
        setIsLoading(true)
        setShowPopUp(false);
        try {

          const { hash } = await writeContract({
            mode: 'recklesslyUnprepared',
            abi: contractInfo.abi,
            address: contractInfo.address as `0x${string}`,
            functionName: 'lockLeasingRigth',
            args: [house.id],
            overrides: {
              value: house.minimumContribution,
            },
          })
          console.log(hash);
        } catch (e: any) {
          toast.error('Error al realizar la separación del leasing.');
          console.log("El error es: ", e.message)
        }
        setIsLoading(false)
      }
    })
  }

  useEffect(() => {
    console.log(user, isConnected, address)
    if (user || !isConnected) {
      setIsLoading(false)
      return;
    }
    if (address) {
      axios.get(`/api/user/?address=${address}`)
        .then(response => {
          const userApi = response.data
          setUserExist(userApi.message == "OK")
          setUser(userApi.user);
          axios.get(`/api/house`)
            .then(response => {
              const housesApi = response.data
              setHouses(housesApi.houses);
              setIsLoading(false);
            })
            .catch(error => {
              console.log("El error es: ", error.response.data.message)
              setIsLoading(false);
            });
        })
        .catch(error => {
          setUserExist(false)
          console.log("El error es: ", error.response.data.message)
          setIsLoading(false);
        });

    } else {
      setIsLoading(false);
    }
  }, [address])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Loading loading={isLoading} />
        <Popup show={showPopUp} myHouse={myHouse} />
        <Navbar page={"index"} />
        {!isLoading && ((userExist && address) ? <div className={styles.main_body}>
          <p className={styles.main_p}>
            A continuación, verás en verde las viviendas que puedes adquirir mediante
            el servicio de leasing inmobiliario de Bancolombia, si está en rojo no te
            preocupes, sigue luchando por tus sueños, y poco a poco cumplirás tus
            metas, en Bancolombia estamos para apoyarte en tu camino
          </p>
          <HomeBody houses={houses} user={user} tryToBuy={tryToBuy} />
        </div> : address ? <p> Te invitamos a acercarte a las oficinas de Bancolombia para
          completar tu registro, de esta manera podrás acceder a este y más
          beneficios.
        </p> : <p>Te invitamos a conectar tu wallet para acceder a los beneficios
          Bancolombia
        </p>)}
      </main>
    </>
  )
}
