import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/navbar'
import { useEffect, useState } from 'react'
import { useAccount } from "wagmi";
import axios from 'axios';
import { User } from "../types/index";
import Loading from '@/components/loading'
import HomeBody from '@/components/home'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { isConnected, address } = useAccount();
  const [user, setUser] = useState<User | undefined>(undefined);
  const [userExist, setUserExist] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  useEffect(() => {
    console.log(user, isConnected, address)
    if (user) return;
    if (!isConnected) return;
    if (address) {
      axios.get(`/api/user/?address=${address}`)
        .then(response => {
          const userApi = response.data
          setUserExist(userApi.message == "OK")
          setUser(userApi.user);
          setIsLoading(false);
        })
        .catch(error => {
          setUserExist(false)
          console.log("El error es: ", error.response.data.message)
          setIsLoading(false);
        });
    }
  }, [address])
  return (
    <>
      <Loading loading={isLoading} />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        {!isLoading && (userExist ? <p className={styles.main_p}>
          A continuación, verás en verde las viviendas que puedes adquirir mediante
          el servicio de leasing inmobiliario de Bancolombia, si está en rojo no te
          preocupes, sigue luchando por tus sueños, y poco a poco cumplirás tus
          metas, en Bancolombia estamos para apoyarte en tu camino
        </p> : <p> Te invitamos a acercarte a las oficinas de Bancolombia para
          completar tu registro, de esta manera podrás acceder a este y más
          beneficios.
        </p>)}
        <HomeBody/>

      </main>
    </>
  )
}
